name: templatecorr_nocan

channels:
  - conda-forge
  - rdkit

dependencies:
  - python>=3.6
  - numpy
  - pip
  - rdkit
  - pandas
  - tensorflow=2.0.0
  - joblib
  - tqdm
  - scikit-learn=0.24
  - pip:
     - git+https://github.com/hesther/rdchiral.git

